data:
    input_feature: title
    output_feature: genre

splitting:
    shuffle: true
    train_size: 0.7
    val_size: 0.15
    test_size: 0.15
    min_samples_per_class: 5

preprocessing:
    lower: true
    char_level: false
    filters: '!"#$%&()*+,-./:;<=>?@[\\]^_`{|}~\t\n'
    min_token_frequency: 3

model:
    cnn:
        filter_sizes: [2, 3, 4, 5]
        num_filters: 50
    embeddings:
        embedding_dim: 256
        freeze_embeddings: false
    fc:
        dropout_p: 0.8
        hidden_dim: 50

training:
    num_epochs: 1
    batch_size: 128
    learning_rate: 0.001
    early_stopping_criteria: 3
    cuda: false
